/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

/**
 *
 * @author lahcen
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        customPanel1.runCircle();
        customPanel2.runCircle();
        customPanel3.runCircle();
        customPanel4.runCircle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        customPanel1 = new com.CustomPanel();
        customPanel2 = new com.CustomPanel();
        customPanel3 = new com.CustomPanel();
        customPanel4 = new com.CustomPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(42, 36, 38));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(254, 84, 69));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(102, 102, 102));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 160, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 12, 15, 15));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reduire.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 12, 15, 15));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/heart.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 15, 15));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(70, 53, 59));
        jLabel20.setText("myHealth App");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 11, 90, 20));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/009.png"))); // NOI18N
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 20, 20));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 200, 20));

        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 10, 25, 20));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 10, 20, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jPanel3.setBackground(new java.awt.Color(70, 53, 59));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(50, 39, 45));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/001.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 15, 15));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(138, 127, 131));
        jLabel4.setText("Dashboard");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 70, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanel5.setBackground(new java.awt.Color(70, 53, 59));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/002.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 15, 15));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(138, 127, 131));
        jLabel6.setText("Log");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 60, 20));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 40));

        jPanel6.setBackground(new java.awt.Color(70, 53, 59));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/003.png"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 15, 15));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(138, 127, 131));
        jLabel8.setText("Steps");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 60, 20));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 40));

        jPanel7.setBackground(new java.awt.Color(70, 53, 59));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/004.png"))); // NOI18N
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 15, 15));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(138, 127, 131));
        jLabel10.setText("Calories");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 60, 20));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 110, 40));

        jPanel8.setBackground(new java.awt.Color(70, 53, 59));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/005.png"))); // NOI18N
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 15, 15));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(138, 127, 131));
        jLabel12.setText("Distance");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 60, 20));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 110, 40));

        jPanel9.setBackground(new java.awt.Color(70, 53, 59));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/006.png"))); // NOI18N
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 15, 15));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(138, 127, 131));
        jLabel14.setText("Time");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 60, 20));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 110, 40));

        jPanel10.setBackground(new java.awt.Color(70, 53, 59));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/007.png"))); // NOI18N
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 15, 15));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(138, 127, 131));
        jLabel16.setText("Friends");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 60, 20));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 110, 40));

        jPanel11.setBackground(new java.awt.Color(70, 53, 59));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/008.png"))); // NOI18N
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 15, 15));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(138, 127, 131));
        jLabel18.setText("Reports");
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, 60, 20));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 460));

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 15, 15));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.png"))); // NOI18N
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 30, 15, 15));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("<html>\n<body>\n<p style=\"text-align:center;font-weight:bold;\">23</p>\n<pstyle=\"text-align:center;\">Mon</p>\n</body>\n</html>");
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, 22, 26));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(132, 92, 106));
        jLabel24.setText("<html>\n<body>\n<p style=\"text-align:center;font-weight:bold;\">28</p>\n<pstyle=\"text-align:center;\">Sat</p>\n</body>\n</html>");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 28, 16, 20));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(132, 92, 106));
        jLabel25.setText("<html>\n<body>\n<p style=\"text-align:center;font-weight:bold;\">22</p>\n<pstyle=\"text-align:center;\">Sun</p>\n</body>\n</html>");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 28, 16, 20));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(252, 71, 80));
        jLabel26.setText("<html>\n<body>\n<p style=\"text-align:center;font-weight:bold;\">25</p>\n<pstyle=\"text-align:center;\">Wends</p>\n</body>\n</html>");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 24, 42, 30));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("<html>\n<body>\n<p style=\"text-align:center;font-weight:bold;\">26</p>\n<pstyle=\"text-align:center;\">Thurs</p>\n</body>\n</html>");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 25, 40, 26));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("<html>\n<body>\n<p style=\"text-align:center;font-weight:bold;\">27</p>\n<pstyle=\"text-align:center;\">Fri</p>\n</body>\n</html>");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 25, 28, 26));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("<html>\n<body>\n<p style=\"text-align:center;font-weight:bold;\">24</p>\n<pstyle=\"text-align:center;\">Tues</p>\n</body>\n</html>");
        jPanel12.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 25, 28, 26));

        customPanel1.setBackground(new java.awt.Color(42, 36, 38));
        customPanel1.setBoucle(40);
        customPanel1.setColorCercle(new java.awt.Color(42, 36, 38));
        customPanel1.setColorLine(new java.awt.Color(113, 226, 224));
        customPanel1.setColorNot(new java.awt.Color(28, 24, 25));
        customPanel1.setNbr(60);
        customPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(customPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 130));

        customPanel2.setBackground(new java.awt.Color(42, 36, 38));
        customPanel2.setBoucle(83);
        customPanel2.setColorCercle(new java.awt.Color(42, 36, 38));
        customPanel2.setColorLine(new java.awt.Color(252, 128, 40));
        customPanel2.setColorNot(new java.awt.Color(28, 24, 25));
        customPanel2.setNbr(60);

        javax.swing.GroupLayout customPanel2Layout = new javax.swing.GroupLayout(customPanel2);
        customPanel2.setLayout(customPanel2Layout);
        customPanel2Layout.setHorizontalGroup(
            customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        customPanel2Layout.setVerticalGroup(
            customPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel12.add(customPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, 130));

        customPanel3.setBackground(new java.awt.Color(42, 36, 38));
        customPanel3.setBoucle(56);
        customPanel3.setColorCercle(new java.awt.Color(42, 36, 38));
        customPanel3.setColorLine(new java.awt.Color(176, 82, 241));
        customPanel3.setColorNot(new java.awt.Color(28, 24, 25));
        customPanel3.setNbr(60);

        javax.swing.GroupLayout customPanel3Layout = new javax.swing.GroupLayout(customPanel3);
        customPanel3.setLayout(customPanel3Layout);
        customPanel3Layout.setHorizontalGroup(
            customPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        customPanel3Layout.setVerticalGroup(
            customPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel12.add(customPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, 130));

        customPanel4.setBackground(new java.awt.Color(42, 36, 38));
        customPanel4.setBoucle(90);
        customPanel4.setColorCercle(new java.awt.Color(42, 36, 38));
        customPanel4.setColorLine(new java.awt.Color(254, 202, 66));
        customPanel4.setColorNot(new java.awt.Color(28, 24, 25));
        customPanel4.setNbr(60);

        javax.swing.GroupLayout customPanel4Layout = new javax.swing.GroupLayout(customPanel4);
        customPanel4.setLayout(customPanel4Layout);
        customPanel4Layout.setHorizontalGroup(
            customPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        customPanel4Layout.setVerticalGroup(
            customPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel12.add(customPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, 130));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(176, 82, 241));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Distance");
        jPanel12.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 140, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(113, 226, 224));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Steps");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, 20));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(252, 128, 40));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Calories");
        jPanel12.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 140, 20));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(254, 202, 66));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Time");
        jPanel12.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 140, 20));

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Friends");
        jPanel13.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel40.setBackground(new java.awt.Color(28, 24, 25));
        jLabel40.setOpaque(true);
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 250, 2));

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/friend2.png"))); // NOI18N
        jPanel14.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("<html>\n<head>\n<style>\np{\n  font-size:6px;\n color:#e8e3e7;\n}\nspan{\n  font-size:8px;\n  color:#e8e3e7;\n  font-weight:bold;\n}\n</style>\n<body>\n<p><span>Lucia Gomez</span> LuciaGomez</p>\n</body>\n</html>");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 20));

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/google.png"))); // NOI18N
        jPanel14.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 20, 20));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 20));

        jLabel44.setBackground(new java.awt.Color(28, 24, 25));
        jLabel44.setOpaque(true);
        jPanel13.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 250, 2));

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/friend1.png"))); // NOI18N
        jPanel15.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("<html>\n<head>\n<style>\np{\n  font-size:6px;\n color:#e8e3e7;\n}\nspan{\n  font-size:8px;\n  color:#e8e3e7;\n  font-weight:bold;\n}\n</style>\n<body>\n<p><span>Gerald Gardner</span> GeraldGardner</p>\n</body>\n</html>");
        jPanel15.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 160, 20));

        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facebook.png"))); // NOI18N
        jPanel15.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 20, 20));

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, 20));

        jPanel16.setOpaque(false);
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/friend3.png"))); // NOI18N
        jPanel16.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("<html>\n<head>\n<style>\np{\n  font-size:6px;\n color:#e8e3e7;\n}\nspan{\n  font-size:8px;\n  color:#e8e3e7;\n  font-weight:bold;\n}\n</style>\n<body>\n<p><span>Luren Halt</span> LurenHalt</p>\n</body>\n</html>");
        jPanel16.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 20));

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/twitter.png"))); // NOI18N
        jPanel16.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 20, 20));

        jPanel13.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 250, 20));

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/friend1.png"))); // NOI18N
        jPanel17.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("<html>\n<head>\n<style>\np{\n  font-size:6px;\n color:#e8e3e7;\n}\nspan{\n  font-size:8px;\n  color:#e8e3e7;\n  font-weight:bold;\n}\n</style>\n<body>\n<p><span>Douglas Rice</span> DouglasRice</p>\n</body>\n</html>");
        jPanel17.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 20));

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facebook.png"))); // NOI18N
        jPanel17.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 20, 20));

        jPanel13.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 20));

        jLabel57.setBackground(new java.awt.Color(28, 24, 25));
        jLabel57.setOpaque(true);
        jPanel13.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 250, 2));

        jLabel58.setBackground(new java.awt.Color(28, 24, 25));
        jLabel58.setOpaque(true);
        jPanel13.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 250, 2));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 230, 150));

        jPanel18.setOpaque(false);
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar1.png"))); // NOI18N
        jLabel68.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel18.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 97, 20, 20));

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar2.png"))); // NOI18N
        jLabel67.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel18.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 17, 20, 100));

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar1.png"))); // NOI18N
        jLabel66.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel18.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 87, 20, 30));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar2.png"))); // NOI18N
        jLabel65.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel18.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 67, 20, 50));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar1.png"))); // NOI18N
        jLabel64.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel18.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 77, 20, 40));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar2.png"))); // NOI18N
        jLabel63.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel18.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 27, 20, 90));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar1.png"))); // NOI18N
        jLabel62.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel18.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 67, 20, 50));

        jLabel38.setBackground(new java.awt.Color(28, 24, 25));
        jLabel38.setOpaque(true);
        jPanel18.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 115, 340, 2));

        jLabel54.setBackground(new java.awt.Color(28, 24, 25));
        jLabel54.setOpaque(true);
        jPanel18.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 340, 2));

        jLabel55.setBackground(new java.awt.Color(28, 24, 25));
        jLabel55.setOpaque(true);
        jPanel18.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 65, 340, 2));

        jLabel56.setBackground(new java.awt.Color(28, 24, 25));
        jLabel56.setOpaque(true);
        jPanel18.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 75, 340, 2));

        jLabel59.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("0%");
        jPanel18.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 20, 20));

        jLabel60.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("5%");
        jPanel18.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 20, 20));

        jLabel61.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("10%");
        jPanel18.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 25, 20));

        jLabel69.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("Mon");
        jPanel18.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 120, 20, 20));

        jLabel70.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Sun");
        jPanel18.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 20, 20));

        jLabel71.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("Thues");
        jPanel18.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 120, 30, 20));

        jLabel72.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Wends");
        jPanel18.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 120, 35, 20));

        jLabel73.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Thurs");
        jPanel18.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 120, 30, 20));

        jLabel74.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("Fri");
        jPanel18.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 120, 20, 20));

        jLabel75.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("Sat");
        jPanel18.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 20, 20));

        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel76.setText("Step taken this week");
        jPanel18.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 260, -1));

        jPanel12.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 350, 150));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 690, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.CustomPanel customPanel1;
    private com.CustomPanel customPanel2;
    private com.CustomPanel customPanel3;
    private com.CustomPanel customPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
